#!/usr/bin/env python3
"""Rebuild search-index.js from the articles themselves.

Run this after adding or editing an article:
    python3 build_search_index.py

The homepage loads the generated file and merges it into its built-in index, so
search covers section headings, named sources and distinctive terms from the
article body, not only the one-line description.
"""
import re
import glob
import html
import json
import collections
from bs4 import BeautifulSoup

SKIP = {'index.html', 'methodology.html', 'support.html', '404.html'}

STOP = set((
    "the a an and or but if then than that this these those with without within into onto from for "
    "to of in on at by as is are was were be been being it its their there here what when where which "
    "who whom whose how why not no nor only just also very more most much many some any each every all "
    "both few other another one two three four five six seven eight nine ten first second third new old "
    "same different such about over under between across during before after while since until because "
    "so however though although yet still even they them he she his her we our you your i me my us can "
    "could would should may might must will shall do does did done has have had having said says say "
    "according per among against toward towards through up down out off again further once article data "
    "study studies research report reports evidence claim claims source sources figure figures percent "
    "number numbers rate rates year years people"
).split())


def article_terms(path):
    t = open(path, encoding='utf-8').read()
    s = BeautifulSoup(t, 'html.parser')
    for el in s.select('script,style,nav,footer,.ymal-section,.support-note,.sources-bar,.cite-this'):
        el.decompose()

    terms = []

    # the article's own section headings name its subtopics
    for h in s.find_all(['h2', 'h3']):
        txt = re.sub(r'\s+', ' ', h.get_text(' ')).strip()
        if txt:
            terms.append(txt)

    body = re.sub(r'\s+', ' ', html.unescape(s.get_text(' ')))
    caps = re.findall(r"\b[A-Z][A-Za-z0-9&'\-]{2,}(?:\s+[A-Z][A-Za-z0-9&'\-]{2,}){0,2}", body)
    acronyms = re.findall(r'\b[A-Z]{2,6}\b', body)

    counts = collections.Counter()
    for c in caps + acronyms:
        c = c.strip()
        if len(c) < 3 or c.lower() in STOP:
            continue
        counts[c] += 1

    # names that recur, which filters out ordinary sentence-initial words
    terms += [w for w, n in counts.most_common(250) if n >= 2]
    # single-mention capitalised names are still worth indexing when they are specific
    terms += [w for w, n in counts.items() if n == 1 and len(w) > 5 and ' ' not in w][:60]

    # the bibliography names sources a reader may search for directly
    for it in s.select('.source-item strong'):
        terms.append(re.sub(r'\s+', ' ', it.get_text(' ')).strip())

    # distinctive lower-case vocabulary is added later, once every article has been read
    seen = set()
    out = []
    for w in terms:
        k = w.lower()
        if k in seen or k in STOP:
            continue
        seen.add(k)
        out.append(w)
    return out


def body_words(path):
    t = open(path, encoding='utf-8').read()
    s = BeautifulSoup(t, 'html.parser')
    for el in s.select('script,style,nav,footer,.ymal-section,.support-note,.sources-bar,.cite-this'):
        el.decompose()
    body = html.unescape(s.get_text(' ')).lower()
    return collections.Counter(w for w in re.findall(r"[a-z][a-z\-']{3,}", body) if w not in STOP)


def main():
    files = [f for f in sorted(glob.glob('*.html')) if f not in SKIP and not f.startswith('google')]
    index = {}
    for f in files:
        index['/' + f[:-5]] = article_terms(f)

    # words that appear in few articles are the ones worth indexing; common ones carry no signal
    per_file = {f: body_words(f) for f in files}
    doc_freq = collections.Counter()
    for c in per_file.values():
        for w in c:
            doc_freq[w] += 1
    for f in files:
        key = '/' + f[:-5]
        have = {t.lower() for t in index[key]}
        distinctive = [w for w, n in per_file[f].items()
                       if n >= 2 and doc_freq[w] <= 4 and w not in have]
        distinctive.sort(key=lambda w: (-per_file[f][w], w))
        index[key] += distinctive[:120]

    payload = ("/* Generated by build_search_index.py. Do not edit by hand. */\n"
               "window.TB_SEARCH_TERMS = "
               + json.dumps(index, ensure_ascii=False, separators=(',', ':')) + ";\n")
    open('search-index.js', 'w', encoding='utf-8').write(payload)
    print("search-index.js written:", len(payload), "bytes,", len(index), "articles,",
          sum(len(v) for v in index.values()), "terms")


if __name__ == '__main__':
    main()
